r"""Freeze the updater into MisteryUpdate.exe.

    python packaging\build_updater.py

Produces packaging\out\dist\MisteryUpdate.exe — one file, no folder, because it
lives beside Mistery.exe in the install folder and a second _internal\ there
would collide with the app's. It is the only onefile exe in this project:
onefile unpacks itself into %TEMP% on every start, which for the 9 MB updater
is a few hundred milliseconds once an hour and for the 174 MB app would be
unbearable, which is why build_app.py is onedir.

Windowed, not console: the scheduled task fires every hour whether or not
anybody is at the keyboard, and a console window flashing up hourly is the kind
of thing that makes people uninstall an app. `--status` and `--check-now` still
print, because main.py attaches to the console of whoever started it when there
is one.

**The key check is the point of this script.** It refuses to build unless the
public key compiled into updater/keys.py is the same key as
packaging/public_key.txt, which is the key the release workflow signs with. The
two drifting apart produces an exe that rejects every real update — quietly,
on other people's machines, weeks later. Use --allow-no-key only for a build
that is never meant to update anything, such as the ones the tests make.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
NAME = "MisteryUpdate"

sys.path.insert(0, str(HERE))
from build_app import app_version            # noqa: E402 - same version, one reader

PUBLIC_KEY_FILE = HERE / "public_key.txt"
KEYS_FILE = ROOT / "updater" / "keys.py"

# The updater needs ssl, urllib, zipfile, hashlib, json and ctypes. Everything
# below is stdlib it will never touch, and each one is a megabyte or two of
# download for every person who installs Mistery.
EXCLUDED_MODULES = (
    "tkinter", "test", "pydoc_data", "unittest", "sqlite3", "lib2to3",
    "distutils", "xml", "PIL", "numpy", "PySide6",
)


def key_in_updater() -> str:
    """The base64 key compiled into updater/keys.py, read rather than imported."""
    text = KEYS_FILE.read_text(encoding="utf-8")
    match = re.search(r'^UPDATE_PUBLIC_KEY\s*=\s*["\']([^"\']*)["\']', text, re.M)
    if not match:
        raise SystemExit(f"no UPDATE_PUBLIC_KEY line in {KEYS_FILE}")
    return match.group(1).strip()


def key_on_file() -> str:
    """The key packaging/public_key.txt holds, or "" if it has not been made yet."""
    if not PUBLIC_KEY_FILE.is_file():
        return ""
    return PUBLIC_KEY_FILE.read_text(encoding="utf-8").strip()


def check_keys(allow_no_key: bool) -> str:
    compiled_in, on_file = key_in_updater(), key_on_file()
    if compiled_in and on_file and compiled_in != on_file:
        raise SystemExit(
            f"\nThe updater would trust a different key from the one releases are\n"
            f"signed with, so every update it is offered would be rejected.\n"
            f"    updater/keys.py           {compiled_in[:16]}...\n"
            f"    packaging/public_key.txt  {on_file[:16]}...\n"
            f"Paste the line from public_key.txt into UPDATE_PUBLIC_KEY and build again.\n")
    if not compiled_in and not allow_no_key:
        raise SystemExit(
            f"\nupdater/keys.py has no UPDATE_PUBLIC_KEY, so this exe would refuse\n"
            f"every update it is ever offered. Run\n"
            f"    python packaging\\make_key.py --out %USERPROFILE%\\Documents\\mistery-signing.key\n"
            f"once, paste the public key it prints into {KEYS_FILE.name}, and build again.\n"
            f"If you meant to build an updater that trusts nothing, pass --allow-no-key.\n")
    return compiled_in


def write_version_resource(path: Path, version: str) -> Path:
    """MisteryUpdate.exe's own VERSIONINFO.

    Its own rather than the app's: Explorer's Properties tab and any antivirus
    report that lists what is running should say what this program is, and
    "Mistery.exe" on a file called MisteryUpdate.exe is how a reasonable person
    concludes something is wrong.
    """
    numbers = tuple([int(n) for n in re.findall(r"\d+", version)][:4] + [0] * 4)[:4]
    path.write_text(f"""# Generated by packaging/build_updater.py — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numbers},
    prodvers={numbers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Mistery'),
         StringStruct('FileDescription', 'Mistery updater'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', 'MisteryUpdate'),
         StringStruct('OriginalFilename', 'MisteryUpdate.exe'),
         StringStruct('ProductName', 'Mistery'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""", encoding="utf-8")
    return path


def build(out_root: Path, allow_no_key: bool = False, keep_work: bool = False) -> Path:
    version = app_version()
    compiled_key = check_keys(allow_no_key)

    # Into the frozen bundle beside Mistery.exe, which is where it lives once
    # installed and where make_package.py and build_setup.py look for it. Run
    # this *after* build_app.py: that one deletes the bundle folder first, and
    # would take the updater with it.
    dist = out_root / "dist" / "Mistery"
    work = out_root / "build-updater"
    out_root.mkdir(parents=True, exist_ok=True)

    resource = write_version_resource(out_root / "updater_version_info.txt", version)
    icon = ROOT / "assets" / "icon.ico"

    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--name", NAME,
        "--onefile",
        "--windowed",
        "--version-file", str(resource),
        "--distpath", str(dist),
        "--workpath", str(work),
        "--specpath", str(out_root),
        "--log-level", "WARN",
    ]
    if icon.is_file():
        command += ["--icon", str(icon)]
    for name in EXCLUDED_MODULES:
        command += ["--exclude-module", name]
    command.append(str(HERE / "updater_entry.py"))

    print(f"building {NAME} {version} with {sys.executable}")
    print(f"  trusts key       {compiled_key[:16] + '...' if compiled_key else '(nothing)'}")
    started = time.monotonic()
    result = subprocess.run(command, cwd=str(ROOT))   # cwd=ROOT so `updater` imports
    if result.returncode != 0:
        raise SystemExit(f"PyInstaller failed ({result.returncode})")
    took = time.monotonic() - started

    exe = dist / f"{NAME}.exe"
    if not exe.is_file():
        raise SystemExit(f"the build finished but {exe} is not there")
    if not keep_work:
        shutil.rmtree(work, ignore_errors=True)

    print(f"\n{exe}")
    print(f"  {exe.stat().st_size / 1e6:.1f} MB, built in {took:.0f} s")
    return exe


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Freeze MisteryUpdate.exe.")
    parser.add_argument("--out", default=str(ROOT / "packaging" / "out"))
    parser.add_argument("--allow-no-key", action="store_true",
                        help="build an updater that trusts nothing (tests only)")
    parser.add_argument("--keep-work", action="store_true")
    args = parser.parse_args(argv)
    build(Path(os.path.expandvars(args.out)).resolve(),
          allow_no_key=args.allow_no_key, keep_work=args.keep_work)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
