"""Freeze Mistery into a folder that runs on a Windows PC with no Python.

    python packaging/build_app.py

Produces packaging\\out\\dist\\Mistery\\ — Mistery.exe, version.txt and the
_internal\\ payload PyInstaller writes beside it. That folder is what the
installer copies into %LOCALAPPDATA%\\Programs\\Mistery.

Two choices worth knowing about:

onedir, never onefile. This build is 181.7 MB in 243 files (measured, version
1.2.0), 93 MB of it Qt. A onefile exe would unpack all of that into %TEMP% on
every single start and delete it again on exit, so every launch pays for it.
Worse for us: the updater replaces files in place, and there are no files
inside a onefile exe to replace.

The version is read out of app/__init__.py and put in three places that all have
to agree: the Windows version resource in the exe (what Explorer's Properties
shows), version.txt beside the exe (what the updater compares, so it needs no
Python), and whatever the installer writes into Add/Remove Programs.

Needs the app's own dependencies importable as well as PyInstaller, because
PyInstaller freezes what it can import: run it from an environment where
`pip install -r requirements.txt pyinstaller` has been done. The build takes
34 s on the machine this was written on.

What to run afterwards, in order:

    python packaging/test_frozen_paths.py   the path logic, no build needed
    python packaging/smoke_frozen.py        starts the real exe, twice
    python packaging/smoke_repair.py        a damaged library, repaired and
                                            restarted by the frozen app
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_NAME = "Mistery"

# The app imports these at startup or on its first music page. PyInstaller
# reports a missing one as a warning halfway through a five-minute build and
# then ships a bundle that dies on launch, so check first and say so plainly.
REQUIRED_MODULES = ("PySide6", "PIL", "requests", "mutagen", "numpy", "cryptography")

# Imported inside a function (main._repair_and_restart), which PyInstaller does
# find on its own — named here so a future refactor of that import cannot
# quietly drop the repair tool out of the bundle.
HIDDEN_IMPORTS = ("tools.repair_db",)

# tkinter is 8 MB of Tcl/Tk for a GUI toolkit the app does not use. (The
# installer does use it — that is a separate build.)
#
# cryptography was excluded here until 1.2.0, when nothing in Mistery used it
# (9.5 MB, most of it one _rust.pyd). Movie night makes each session's TLS
# certificate with it, so it ships now, and check_movie_night() below proves it
# is in the bundle: a bundle without it starts fine and fails only when a host
# presses Start movie night, on a PC where nobody can see why.
EXCLUDED_MODULES = ("tkinter", "test", "pydoc_data")

# What movie night needs, looked for inside the finished exe rather than trusted
# to PyInstaller's analysis. Every one is imported at the top of a module, so
# the analysis does find them today; this is here for the day a refactor moves
# an import into a function behind a string, or someone excludes a package again.
MOVIE_NIGHT_MODULES = (
    "app.party.session", "app.party.server", "app.party.sync", "app.party.tls",
    "app.party.invite", "app.party.upnp", "app.party.stun", "app.party.guest_proxy",
    "app.party.transcode", "app.party.people", "app.ui.party_dialog",
    "cryptography.x509", "cryptography.hazmat.primitives.asymmetric.ec", "ssl",
)


def app_version() -> str:
    """The version in app/__init__.py, read rather than imported.

    Importing app would pull in PySide6 and build a Settings object; a build
    script has no business doing either.
    """
    text = (ROOT / "app" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', text, re.M)
    if not match:
        raise SystemExit("could not find __version__ in app/__init__.py")
    return match.group(1)


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    """1.2.3 as the four numbers a Windows version resource wants."""
    parts = [int(n) for n in re.findall(r"\d+", version)][:4]
    return tuple(parts + [0] * (4 - len(parts)))            # type: ignore[return-value]


def write_version_resource(path: Path, version: str) -> Path:
    """The VERSIONINFO block PyInstaller stamps into Mistery.exe.

    Without it Explorer's Properties tab has no Details and Add/Remove Programs
    has nothing to agree with, so an installed Mistery would claim no version at
    all while version.txt beside it said 1.0.0.
    """
    numbers = _version_tuple(version)
    path.write_text(f"""# Generated by packaging/build_app.py — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numbers},
    prodvers={numbers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Mistery'),
         StringStruct('FileDescription', 'Mistery — movies, shows and music'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', 'Mistery'),
         StringStruct('OriginalFilename', 'Mistery.exe'),
         StringStruct('ProductName', 'Mistery'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""", encoding="utf-8")
    return path


def _missing_modules() -> list[str]:
    import importlib.util

    missing = []
    for name in REQUIRED_MODULES + ("PyInstaller",):
        try:
            if importlib.util.find_spec(name) is None:
                missing.append(name)
        except Exception:                       # a broken install reads as missing
            missing.append(name)
    return missing


def exe_file_version(exe: Path) -> str | None:
    """The FileVersion string Explorer's Properties tab shows for an exe.

    Read back out of the built file rather than assumed: PyInstaller stamps the
    resource from the text file we generate for it, and a mistake in that file
    is not an error, it is an exe with no version at all — which Add/Remove
    Programs would then disagree with. ctypes and version.dll rather than
    pywin32, which is not worth adding as a build dependency for ten lines.
    """
    if os.name != "nt":
        return None
    import ctypes
    from ctypes import wintypes

    version_dll = ctypes.WinDLL("version", use_last_error=True)
    version_dll.GetFileVersionInfoSizeW.argtypes = (wintypes.LPCWSTR, wintypes.LPDWORD)
    version_dll.GetFileVersionInfoSizeW.restype = wintypes.DWORD
    version_dll.GetFileVersionInfoW.argtypes = (
        wintypes.LPCWSTR, wintypes.DWORD, wintypes.DWORD, wintypes.LPVOID)
    version_dll.GetFileVersionInfoW.restype = wintypes.BOOL
    version_dll.VerQueryValueW.argtypes = (
        wintypes.LPVOID, wintypes.LPCWSTR,
        ctypes.POINTER(wintypes.LPVOID), ctypes.POINTER(wintypes.UINT))
    version_dll.VerQueryValueW.restype = wintypes.BOOL

    size = version_dll.GetFileVersionInfoSizeW(str(exe), None)
    if not size:
        return None
    buffer = ctypes.create_string_buffer(size)
    if not version_dll.GetFileVersionInfoW(str(exe), 0, size, buffer):
        return None
    value = wintypes.LPVOID()
    length = wintypes.UINT()
    # 040904B0 — US English, Unicode: the one block write_version_resource writes.
    if not version_dll.VerQueryValueW(
            buffer, r"\StringFileInfo\040904B0\FileVersion",
            ctypes.byref(value), ctypes.byref(length)):
        return None
    return ctypes.wstring_at(value.value, length.value).rstrip("\0")


def modules_in_exe(exe: Path) -> set[str]:
    """The pure-Python modules frozen into the exe's PYZ archive, read back out
    of the exe with PyInstaller's own reader (825 of them in the 1.1.0 build)."""
    from PyInstaller.archive.readers import CArchiveReader

    archive = CArchiveReader(str(exe))
    pyz = next(name for name in archive.toc if name.endswith(".pyz"))
    return set(archive.open_embedded_archive(pyz).toc)


def check_movie_night(bundle: Path, exe: Path) -> int:
    """Raise unless everything movie night needs is in the bundle. Returns how
    many modules were checked, for the report."""
    frozen = modules_in_exe(exe)
    missing = [name for name in MOVIE_NIGHT_MODULES if name not in frozen]
    # cryptography's compiled half, OpenSSL included, is one file beside the exe.
    rust = bundle / "_internal" / "cryptography" / "hazmat" / "bindings" / "_rust.pyd"
    if not rust.is_file():
        missing.append(str(rust.relative_to(bundle)))
    if missing:
        raise SystemExit("the build is missing what movie night needs: " + ", ".join(missing))
    return len(MOVIE_NIGHT_MODULES)


def folder_size(folder: Path) -> tuple[int, int]:
    """(bytes, files) under a folder, for the build report."""
    total = files = 0
    for path in folder.rglob("*"):
        if path.is_file():
            total += path.stat().st_size
            files += 1
    return total, files


def build(out_root: Path, keep_work: bool = False) -> Path:
    version = app_version()
    missing = _missing_modules()
    if missing:
        raise SystemExit(
            "cannot build: " + ", ".join(missing) + " not importable by "
            f"{sys.executable}.\nInstall them first:\n"
            f'    "{sys.executable}" -m pip install -r requirements.txt pyinstaller'
        )

    dist = out_root / "dist"
    work = out_root / "build"
    out_root.mkdir(parents=True, exist_ok=True)
    # A stale Mistery\ from an older version would keep files the new build no
    # longer has, and the installer would ship them.
    shutil.rmtree(dist / APP_NAME, ignore_errors=True)

    version_file = write_version_resource(out_root / "version_info.txt", version)
    icon = ROOT / "assets" / "icon.ico"

    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        "--name", APP_NAME,
        "--windowed",               # no console window behind the app
        "--icon", str(icon),
        "--version-file", str(version_file),
        # Into _internal\assets. app.config.assets_dir() looks there when frozen.
        "--add-data", f"{ROOT / 'assets'}{os.pathsep}assets",
        "--distpath", str(dist),
        "--workpath", str(work),
        "--specpath", str(out_root),
        "--log-level", "WARN",
    ]
    for name in HIDDEN_IMPORTS:
        command += ["--hidden-import", name]
    for name in EXCLUDED_MODULES:
        command += ["--exclude-module", name]
    command.append(str(ROOT / "main.py"))

    print(f"building Mistery {version} with {sys.executable}")
    started = time.monotonic()
    # cwd=ROOT so PyInstaller's analysis starts where main.py's own imports do.
    result = subprocess.run(command, cwd=str(ROOT))
    if result.returncode != 0:
        raise SystemExit(f"PyInstaller failed ({result.returncode})")
    took = time.monotonic() - started

    bundle = dist / APP_NAME
    exe = bundle / f"{APP_NAME}.exe"
    if not exe.is_file():
        raise SystemExit(f"build finished but {exe} is not there")

    # One line, no BOM, no trailing spaces: the updater reads this with a plain
    # file read and compares it as a version, and it must not need Python to.
    (bundle / "version.txt").write_text(version + "\n", encoding="utf-8")

    # Check the bundle instead of trusting the build. Both of these fail only on
    # the machine the installer ran on: no icon in the payload is a blank window
    # and a blank tray icon, and a version resource that did not get stamped is
    # an Add/Remove Programs entry that reports no version at all.
    icon_in_bundle = bundle / "_internal" / "assets" / "icon.ico"
    if not icon_in_bundle.is_file():
        raise SystemExit(f"the build has no _internal\\assets\\icon.ico ({icon_in_bundle})")
    stamped = exe_file_version(exe)
    if os.name == "nt" and stamped != version:
        raise SystemExit(f"{exe.name} reports FileVersion {stamped!r}, not {version!r}")
    party_checked = check_movie_night(bundle, exe)

    if not keep_work:
        shutil.rmtree(work, ignore_errors=True)

    size, files = folder_size(bundle)
    print(f"\n{bundle}")
    print(f"  Mistery.exe      {exe.stat().st_size / 1e6:.1f} MB")
    print(f"  bundle           {size / 1e6:.1f} MB in {files} files")
    print(f"  version          {version} (exe resource says {stamped}, version.txt agrees)")
    print(f"  icon             _internal\\assets\\icon.ico, "
          f"{icon_in_bundle.stat().st_size / 1024:.0f} KB")
    print(f"  movie night      {party_checked} modules found in the exe, and cryptography's _rust.pyd")
    print(f"  built in         {took:.0f} s")
    return bundle


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Freeze Mistery with PyInstaller.")
    parser.add_argument("--out", default=str(ROOT / "packaging" / "out"),
                        help="where to build (default packaging/out)")
    parser.add_argument("--keep-work", action="store_true",
                        help="keep the PyInstaller work folder for debugging")
    parser.add_argument("--print-version", action="store_true",
                        help="print the version from app/__init__.py and stop")
    args = parser.parse_args(argv)

    if args.print_version:
        print(app_version())
        return 0
    build(Path(args.out).resolve(), keep_work=args.keep_work)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
